es5 compatibility
stevenvachon/camelcase-css pull request #2
Opened 2018-08-03 01:28 UTC by gregplaysguitar

Since this code isn't transpiled, it should use es5 syntax for browser compatibility

2018-08-03 01:30 UTC, samueljseay commented
+1 for this, we use postcss-js in browser which depends on this package and would really like to avoid having to transpile this. 😄

2018-08-03 13:21 UTC, stevenvachon commented
@samueljseay PostCSS is not ES5, so you already have to transpile.

2018-08-03 13:44 UTC, stevenvachon commented
I'm still against releasing ES5 libraries. Transpiling a dependency from ES2015 to ES5 loses advantages and is no different from doing the reverse (with [lebab](https://npmjs.com/lebab) or [uglify-es](https://npmjs.com/uglify-es)).

2018-08-06 02:32 UTC, gregplaysguitar commented
Ok, that's your prerogative; just be aware that we're now going to have to either convince other libs (i.e. postcss-js) not to depend on yours, or inline the code for those libraries, so this seems like a small change with a real benefit.

2018-08-06 17:22 UTC, ai commented
@stevenvachon hi, we need ES5 support for PostCSS. Maybe you can reconsider it?

I think we should be focused on the user first, and only then on developers.

ES6 vs ES6 is not a big deal for 30 lines file. But it is a big deal for users, who can’t update their browsers. There are African users without any computer expect the old non-smartphone phone, which supports only Opera Mini. There are IE users, which can’t update it because they work from Internet cafe.

I agree that in every case it is a question of balance. And I understand when big complex applications start to serve only ES6 compatible JS. But 30 lines dependency is not this case. It is just 5 minutes work (which already done) for you and really hours of help to users without ability to update browsers.

2018-08-07 19:06 UTC, Nedomas commented
+1. It is also breaking the standard `yarn build` in the `create-react-app`.

2018-08-08 02:11 UTC, stevenvachon requested changes

2018-08-08 02:11 UTC, stevenvachon commented on index.js
> +var camelCaseCSS = function (property) {
`function camelCaseCSS(property) {`

2018-08-08 02:11 UTC, stevenvachon commented on index.js
> +var callback = (dashChar, char) => char.toUpperCase();
This will need to be a regular function. With that, I'd prefer not a variable declaration.

2018-08-08 02:14 UTC, stevenvachon commented
@ai doesn't PostCSS use Promises?

2018-08-08 03:10 UTC, ai commented
@stevenvachon yes, but end-users can add polyfill for Promise.

2018-08-08 12:45 UTC, stevenvachon commented
@ai end-users can also run a global transform on their codebase. Similar difference.

2018-08-08 12:48 UTC, stevenvachon commented
How do you all feel about the use of ES2015's `String#startsWith`? It will need a polyfill.

2018-08-08 17:36 UTC, ai commented
Global compilation is much harder, most of developers will afraid of do it.

I try to not use `startsWith`. Send PR if you will find it.

I have a responsibilities about support. This talk will not change them, because I already promised support. So it is not just my thoughts. I have a exact problem.

If you don't want to support big projects and care about compatibility, it is OK. It  doesn't make a bad person. We all just do your hobbies. Just say that this project is just for fun and we will replace dependency or inline code of it.

I don't need to change your mind, I just need to fix exact problem.

2018-08-08 18:20 UTC, stevenvachon commented
Like all of my projects, I wrote them for myself and I share them in an ideal state. There's no point in duplicating code in the world, so I'll conform this library to its needs. I don't want to sacrifice code quality, though, and switching from `startsWith` to `indexOf` is affecting that. I think I'll just add a build step.

2018-08-08 18:27 UTC, ai commented
Build step will not work with `startsWith` since it need a polyfill, not only compiling

2018-08-08 18:33 UTC, stevenvachon commented
https://www.npmjs.com/package/babel-plugin-optimize-starts-with

2018-08-08 18:34 UTC, ai commented
Wow, cool. Didn't know about it. Thanks for the link.

2018-08-08 18:59 UTC, stevenvachon commented
I just pushed the changes. Let me know if it solves the issue and I'll release it.

2018-08-09 12:13 UTC, stevenvachon commented
@ai, @gregplaysguitar, @Nedomas

2018-08-09 14:19 UTC, ai commented
Sorry, I on the Def Con right now

2018-08-09 21:18 UTC, gregplaysguitar commented
`index-es5.js` looks good to me. Just so I'm not misunderstanding, we would import like this? 

`const camelCaseCSS = require('camelcase-css/index-es5');`

2018-08-10 01:42 UTC, ai commented
@gregplaysguitar nope, webpack will replace `index.js` to `index-es5` because of `browser` field in `package.json`

2018-08-10 01:42 UTC, ai commented
LGTM, too :+1:

2018-08-11 01:00 UTC, stevenvachon commented
Released as v2.0.1

Thanks!

2018-08-11 01:00 UTC, closed without merging